#!/usr/bin/env python3
#
# Copyright (c) 2018, Neil Booth
#
# All rights reserved.
#
# See the file "LICENCE" for information about the copyright
# and warranty status of this software.

'''Script to kick off the client.'''

import logging
import traceback

from client.app import App


def main():
    '''Set up logging and run the client.'''
    logging.basicConfig(level=logging.INFO)
    logging.info(f'{App.NAME} starting')

    try:
        app = App()
        app.run()
    except Exception:
        traceback.print_exc()
        logging.critical(f'{App.NAME} terminated abnormally')
    else:
        logging.info(f'{App.NAME} terminated normally')


if __name__ == '__main__':
    main()
